### ISSUE TITLE
api/product/items/search endpoint issues

### ISSUE THREAD

**Issue by nickcoleman** [DobaTech/thanos-api-docs#38]
Following are issues with the api/product/items/search endpoint
[ ]: facets categories no returned in correct structure.
Full tree with multiple branches being returned
What should be returned are the breadcrumbs (precursor parent categories), the currently selected category, and the children of the currently selected category. 
The currently selected category should be returned with selected: true.  selected on all others should be false.  
If at the root level, all root categories should be returned with selected: false

[ ]: facets product_identifiers causes 500 when submited
[ ]: number_of_item_images not returned in the response

**Comment by Gidgidonihah** [comment]
@nickcoleman If this issue is still accurate it should be on the [thanos](https://github.com/DobaTech/thanos/) repo. Please open the corresponding issue there and link to this issue. Then close this issue.

**Comment by nickcoleman** [comment]
No longer an issue
