### ISSUE TITLE
empty search on csv export to return an empty hash

### ISSUE THREAD

**Issue by jtprince** [DobaTech/thanos-api-docs#51]
We never specified the behavior if a search is made in order to export items but there are no items.  If there were items, I'd return an export uuid like this:

`{"export": {"uuid": <some uuid>}}`

If there are no items to export as a result of a search, I return this, for now (can re-visit post Jan 9):

`{"export": {}}`

@baileymatthewr

**Comment by baileymatthewr** [comment]
@jtprince : I just added https://github.com/DobaTech/thanos-api-docs/pull/54 for this specifically
